### ISSUE TITLE
URL Preview should be shown

### ISSUE THREAD

**Issue by edent** [PaulKinlan/qrcode#1]
As a user, I want to see the destination of the URL _before_ I open it.

Currently, I don't see the URL.

![qr no url](https://cloud.githubusercontent.com/assets/837136/6106698/a30cf964-b05b-11e4-9188-b341652d1c0c.jpg)

Firefox 35.0.1 on Ubuntu.

**Comment by PaulKinlan** [comment]
Odd. It should appear. Do you have the qrcode you scanned to hand?

**Comment by edent** [comment]
Generated by the latest zxing on Android Lollipop.
Clicking the "Open" button took me to the correct destination.
![screenshot_2015-02-09-13-11-31](https://cloud.githubusercontent.com/assets/837136/6106908/6e7a9a06-b05d-11e4-8c06-03797383e259.png)

**Comment by PaulKinlan** [comment]
Odd, I get the URL on the screen.  I will investigate further.

**Comment by PaulKinlan** [comment]
![img_0142](https://cloud.githubusercontent.com/assets/45510/19229599/a3e14d0e-8ec6-11e6-9574-52607b738444.PNG)

I am going to close out this issue (I know this is an incredibly old issue) because it WFM and I can't isolate what the differences are.  I've tried it with the new iOS camera method, the old integrated getUserMedia method.
